-- Outbound webhook endpoints per tenant.
--
-- Tenants register HTTP endpoints here; Brain POSTs signed payloads
-- when forwarded audit events occur. Secret is a 32-byte hex HMAC key
-- generated by the server and returned once on creation; never returned
-- on subsequent reads (callers see the masked form).
--
-- enabled_events: NULL = all 9 forwarded event types.
--                 Non-null = customer-selected subset.

BEGIN;

CREATE TABLE IF NOT EXISTS webhook_endpoints (
  id               TEXT        PRIMARY KEY,               -- whe_...
  tenant_id        TEXT        NOT NULL,
  url              TEXT        NOT NULL,
  secret           TEXT        NOT NULL,                  -- raw HMAC key, never returned post-create
  enabled_events   TEXT[],                                -- NULL = all forwarded events
  enabled          BOOLEAN     NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_tenant
  ON webhook_endpoints (tenant_id)
  WHERE enabled = true;

-- RLS: tenants can only see and write their own endpoints.
ALTER TABLE webhook_endpoints ENABLE ROW LEVEL SECURITY;

CREATE POLICY webhook_endpoints_tenant_isolation
  ON webhook_endpoints
  USING (tenant_id = current_setting('app.tenant_id', true))
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

COMMIT;
