/**
 * Skills spec generator.
 *
 * Emits the public-safe spec consumed by the public `brain-skills` repo's
 * drift check. It exports only non-secret definition fields: trigger phrases,
 * evidence names, scopes, risk, and authority. It exports no handlers, policy
 * templates, or logic.
 *
 * Usage (from repo root):
 *   pnpm tsx tools/skills-spec/generate.ts > /tmp/brain-agents.json
 */

import type { InternalAgentDefinition } from "@brain/schemas";
import { internalAgentCatalog } from "../../services/internal-agents/src/registry.js";

const LAUNCH_KEYS = [
  "reconciliation",
  "subscription",
  "vendor_risk",
  "collections",
  "fraud_anomaly",
  "cash_forecast",
  "dispute",
  "payment",
  "treasury",
  "revenue_intel",
  "compliance",
] as const;
const LAUNCH_KEY_SET = new Set<string>(LAUNCH_KEYS);

function publicFields(def: InternalAgentDefinition) {
  return {
    agent_key: def.agent_key,
    display_name: def.display_name,
    category: def.category,
    risk_level: def.risk_level,
    default_authority: def.default_authority,
    has_default_action: Object.prototype.hasOwnProperty.call(def, "default_action"),
    capabilities: def.capabilities,
    minimum_confidence: def.minimum_confidence,
    triggers: def.triggers,
    intent_patterns: def.intent_patterns,
    readable_data: def.readable_data,
    required_evidence: def.required_evidence,
  };
}

function main() {
  const agents: Record<string, ReturnType<typeof publicFields>> = {};
  for (const def of internalAgentCatalog) {
    if (!LAUNCH_KEY_SET.has(def.agent_key)) continue;
    if (def.agent_key in agents) {
      throw new Error(`Duplicate launch agent in catalog: ${def.agent_key}`);
    }
    agents[def.agent_key] = publicFields(def);
  }

  const missing = LAUNCH_KEYS.filter((key) => !(key in agents));
  if (missing.length > 0) {
    throw new Error(`Missing launch agents in catalog: ${missing.join(", ")}`);
  }

  const spec = {
    generated_at: new Date().toISOString(),
    source: "brain-core/services/internal-agents/src",
    note: "Public-safe fields only. Regenerated by tools/skills-spec/generate.ts. Do not hand-edit.",
    agents,
  };

  process.stdout.write(`${JSON.stringify(spec, null, 2)}\n`);
}

main();
